coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default: false

ignore:
  - "cmd/**"
  - "hack/**"
  - "config/**"
  - "vendor/**"
  - "release/**"
  - "bin/**"
