name: Go coverage

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron: '14 3 5 */2 *'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  go-coverage:
    name: Go coverage
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      id-token: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Generate coverage
        run: |
          go test -cover -coverprofile=coverage.txt ./... || true
          echo "Generated coverage profile"

      - name: Archive coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: code-coverage
          path: coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v6.0.2
        with:
          files: coverage.txt
          flags: unit-tests
          use_oidc: true
          fail_ci_if_error: true

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: fgrosse/go-coverage-report@e432de98ee94a276e8f666d25bfd76347665f75b  # v1.3.1
        continue-on-error: true
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
